import type { FC, PointerEvent } from "react";
import { useEffect, useEffectEvent, useMemo, useRef, useState } from "react";

import {
  Card,
  Col,
  Row,
  Slider,
  Space,
  Statistic,
  Switch,
  Tag,
  Typography,
} from "antd";

import {
  clearCache,
  layoutNextLine,
  type PreparedTextWithSegments,
  prepareWithSegments,
  setLocale,
  walkLineRanges,
} from "@chenglou/pretext";

type Interval = {
  left: number;
  right: number;
};

type StageRect = {
  width: number;
  height: number;
};

type ActorState = {
  x: number;
  y: number;
  vx: number;
  vy: number;
  tilt: number;
};

type Obstacle = {
  cx: number;
  cy: number;
  r: number;
  hPad: number;
  vPad: number;
};

type TextFragment = {
  id: string;
  text: string;
  x: number;
  y: number;
  width: number;
  intensity: number;
  slotWidth: number;
};

type LayoutProjection = {
  fragments: TextFragment[];
  consumedRows: number;
  visibleHeight: number;
};

type Star = {
  id: number;
  left: string;
  top: string;
  size: number;
  duration: number;
  delay: number;
  opacity: number;
};

type StatTileProps = {
  label: string;
  value: number;
  suffix?: string;
};

type AstronautSpriteProps = {
  actor: ActorState;
  radius: number;
  stageHeight: number;
};

type PretextCosmicPageProps = unknown;

const BODY_FONT_FAMILY = '"Cormorant Garamond", Georgia, serif';
const BODY_FONT = `500 22px ${BODY_FONT_FAMILY}`;
const BODY_LINE_HEIGHT = 28;
const SLOT_MIN_WIDTH = 84;
const STAGE_PADDING_X = 38;
const STAGE_PADDING_TOP = 42;
const STAGE_PADDING_BOTTOM = 32;
const MAX_TEXT_WIDTH = 980;
const COSMIC_COPY = `THE ASTRONAUT DOES NOT PUSH THE TEXT. THE TEXT MOVES BEFORE IMPACT.

That is the trick that makes Pretext feel supernatural the first time you see it. Nothing in the scene asks the DOM how tall a paragraph is. Nothing waits for a browser layout pass. The words already know how wide they are, and the layout engine only has to decide where they should go.

So when a body enters the field, the paragraph bends. When the traveler drifts to the left edge, the copy compresses and wraps tighter. When the traveler accelerates toward the right, the corridor opens and the sentence stream spills through the cleared channel. You are not watching CSS react after the fact. You are watching text geometry get recomputed as pure arithmetic.

Official Pretext demos prove the point with editorial spreads, shrink-wrapped chat bubbles, and animated orbs. This version takes the same idea and turns it into a stage performance. The pilot glides through a page-sized nebula while nearby lines brighten, tilt, and heat up. The field changes both flow and style. The words do not merely avoid the obstacle; they acknowledge it.

That distinction matters. A normal layout engine gives you boxes. Pretext gives you line boundaries, widths, cursors, and the freedom to compose with them. Once you have that data, text stops behaving like static content and starts behaving like a material.

Move slowly and the body copy forms a calm wake. Sweep hard across the stage and you get a split-channel layout with fragments printed on both sides of the gravity well. Turn on dual core mode and the trailing echo becomes a second obstruction, producing a violent editorial ripple that would be painful to build with DOM measurements.

This is why the library is interesting beyond benchmarks. The speed is not just a nice number. The speed changes what is feasible. A good text engine should let typography participate in interaction design, not sit behind it waiting to be measured.

The best part is that the effect is not fake. The fragments on screen are still real line materializations generated by Pretext. Every move updates the available slots per row. Every slot asks layoutNextLine what fits right now. The visual spectacle comes from a serious API.

The result is dramatic, but the principle is simple: measure once, route forever.`;
const STARS: Star[] = [
  {
    id: 1,
    left: "6%",
    top: "10%",
    size: 3,
    duration: 8.6,
    delay: 0.4,
    opacity: 0.42,
  },
  {
    id: 2,
    left: "12%",
    top: "22%",
    size: 2,
    duration: 10.8,
    delay: 1.7,
    opacity: 0.33,
  },
  {
    id: 3,
    left: "18%",
    top: "14%",
    size: 4,
    duration: 9.2,
    delay: 0.8,
    opacity: 0.48,
  },
  {
    id: 4,
    left: "24%",
    top: "70%",
    size: 2,
    duration: 7.6,
    delay: 2.3,
    opacity: 0.28,
  },
  {
    id: 5,
    left: "29%",
    top: "28%",
    size: 5,
    duration: 11.2,
    delay: 0.1,
    opacity: 0.36,
  },
  {
    id: 6,
    left: "33%",
    top: "56%",
    size: 2,
    duration: 8.1,
    delay: 1.2,
    opacity: 0.39,
  },
  {
    id: 7,
    left: "39%",
    top: "8%",
    size: 3,
    duration: 7.8,
    delay: 1.9,
    opacity: 0.47,
  },
  {
    id: 8,
    left: "44%",
    top: "80%",
    size: 4,
    duration: 12.2,
    delay: 0.5,
    opacity: 0.22,
  },
  {
    id: 9,
    left: "49%",
    top: "18%",
    size: 2,
    duration: 8.9,
    delay: 2.7,
    opacity: 0.44,
  },
  {
    id: 10,
    left: "53%",
    top: "67%",
    size: 3,
    duration: 10.2,
    delay: 0.3,
    opacity: 0.31,
  },
  {
    id: 11,
    left: "58%",
    top: "34%",
    size: 5,
    duration: 9.7,
    delay: 1.4,
    opacity: 0.43,
  },
  {
    id: 12,
    left: "62%",
    top: "12%",
    size: 2,
    duration: 7.1,
    delay: 2.2,
    opacity: 0.29,
  },
  {
    id: 13,
    left: "67%",
    top: "76%",
    size: 3,
    duration: 8.3,
    delay: 1.1,
    opacity: 0.46,
  },
  {
    id: 14,
    left: "71%",
    top: "51%",
    size: 2,
    duration: 12.7,
    delay: 0.9,
    opacity: 0.21,
  },
  {
    id: 15,
    left: "76%",
    top: "21%",
    size: 4,
    duration: 9.4,
    delay: 2.4,
    opacity: 0.4,
  },
  {
    id: 16,
    left: "82%",
    top: "41%",
    size: 2,
    duration: 8.5,
    delay: 0.2,
    opacity: 0.35,
  },
  {
    id: 17,
    left: "87%",
    top: "14%",
    size: 3,
    duration: 11.4,
    delay: 2.1,
    opacity: 0.38,
  },
  {
    id: 18,
    left: "91%",
    top: "63%",
    size: 5,
    duration: 10.6,
    delay: 1.6,
    opacity: 0.3,
  },
];

const clamp = (value: number, min: number, max: number) => {
  return Math.min(Math.max(value, min), max);
};

const lerp = (from: number, to: number, amount: number) => {
  return from + (to - from) * amount;
};

const round = (value: number) => {
  return Number(value.toFixed(1));
};

const getDistance = (x1: number, y1: number, x2: number, y2: number) => {
  return Math.hypot(x1 - x2, y1 - y2);
};

const circleIntervalForBand = (
  obstacle: Obstacle,
  bandTop: number,
  bandBottom: number,
) => {
  const top = bandTop - obstacle.vPad;
  const bottom = bandBottom + obstacle.vPad;

  if (top >= obstacle.cy + obstacle.r || bottom <= obstacle.cy - obstacle.r) {
    return null;
  }

  const minDy =
    obstacle.cy >= top && obstacle.cy <= bottom
      ? 0
      : obstacle.cy < top
        ? top - obstacle.cy
        : obstacle.cy - bottom;

  if (minDy >= obstacle.r) {
    return null;
  }

  const maxDx = Math.sqrt(obstacle.r * obstacle.r - minDy * minDy);

  return {
    left: obstacle.cx - maxDx - obstacle.hPad,
    right: obstacle.cx + maxDx + obstacle.hPad,
  } satisfies Interval;
};

const carveTextLineSlots = (base: Interval, blocked: Interval[]) => {
  let slots = [base];

  for (let blockedIndex = 0; blockedIndex < blocked.length; blockedIndex += 1) {
    const interval = blocked[blockedIndex];
    const nextSlots: Interval[] = [];

    for (let slotIndex = 0; slotIndex < slots.length; slotIndex += 1) {
      const slot = slots[slotIndex];

      if (interval.right <= slot.left || interval.left >= slot.right) {
        nextSlots.push(slot);
        continue;
      }

      if (interval.left > slot.left) {
        nextSlots.push({ left: slot.left, right: interval.left });
      }

      if (interval.right < slot.right) {
        nextSlots.push({ left: interval.right, right: slot.right });
      }
    }

    slots = nextSlots;
  }

  return slots
    .filter((slot) => {
      return slot.right - slot.left >= SLOT_MIN_WIDTH;
    })
    .sort((leftSlot, rightSlot) => {
      return leftSlot.left - rightSlot.left;
    });
};

const getSingleLineWidth = (prepared: PreparedTextWithSegments) => {
  let widestLine = 0;

  walkLineRanges(prepared, 100_000, (line) => {
    widestLine = Math.max(widestLine, line.width);
  });

  return widestLine;
};

const getFragmentIntensity = (
  centerX: number,
  centerY: number,
  obstacles: Obstacle[],
) => {
  let strongest = 0;

  for (
    let obstacleIndex = 0;
    obstacleIndex < obstacles.length;
    obstacleIndex += 1
  ) {
    const obstacle = obstacles[obstacleIndex];
    const distance = getDistance(centerX, centerY, obstacle.cx, obstacle.cy);
    const influence = clamp(1 - distance / (obstacle.r * 1.9), 0, 1);
    strongest = Math.max(strongest, influence);
  }

  return strongest;
};

const buildProjection = (
  prepared: PreparedTextWithSegments,
  stageRect: StageRect,
  actor: ActorState,
  radius: number,
  dualCore: boolean,
) => {
  const availableWidth = Math.min(
    stageRect.width - STAGE_PADDING_X * 2,
    MAX_TEXT_WIDTH,
  );
  const left = (stageRect.width - availableWidth) / 2;
  const top = STAGE_PADDING_TOP;
  const bottom = stageRect.height - STAGE_PADDING_BOTTOM;
  const base: Interval = { left, right: left + availableWidth };
  const fragments: TextFragment[] = [];

  const obstacles: Obstacle[] = [
    {
      cx: actor.x,
      cy: actor.y,
      hPad: 24,
      r: radius * 0.84,
      vPad: 12,
    },
  ];

  if (dualCore) {
    obstacles.push({
      cx: actor.x - actor.vx * 22,
      cy: actor.y - actor.vy * 22 + 8,
      hPad: 14,
      r: radius * 0.42,
      vPad: 8,
    });
  }

  let cursor = { graphemeIndex: 0, segmentIndex: 0 };
  let rowTop = top;
  let consumedRows = 0;

  while (rowTop + BODY_LINE_HEIGHT <= bottom) {
    const bandTop = rowTop;
    const bandBottom = rowTop + BODY_LINE_HEIGHT;
    const blocked = obstacles
      .map((obstacle) => {
        return circleIntervalForBand(obstacle, bandTop, bandBottom);
      })
      .filter((interval): interval is Interval => {
        return interval !== null;
      });
    const slots = carveTextLineSlots(base, blocked);

    if (slots.length === 0) {
      rowTop += BODY_LINE_HEIGHT;
      consumedRows += 1;
      continue;
    }

    for (let slotIndex = 0; slotIndex < slots.length; slotIndex += 1) {
      const slot = slots[slotIndex];
      const line = layoutNextLine(prepared, cursor, slot.right - slot.left);

      if (line === null) {
        return {
          consumedRows,
          fragments,
          visibleHeight: rowTop - top,
        } satisfies LayoutProjection;
      }

      const centerX = slot.left + line.width / 2;
      const centerY = rowTop + BODY_LINE_HEIGHT / 2;
      const intensity = getFragmentIntensity(centerX, centerY, obstacles);

      fragments.push({
        id: `${consumedRows}-${slotIndex}-${line.start.segmentIndex}-${line.end.segmentIndex}`,
        intensity,
        slotWidth: slot.right - slot.left,
        text: line.text,
        width: line.width,
        x: slot.left,
        y: rowTop,
      });

      cursor = line.end;
    }

    rowTop += BODY_LINE_HEIGHT;
    consumedRows += 1;
  }

  return {
    consumedRows,
    fragments,
    visibleHeight: bottom - top,
  } satisfies LayoutProjection;
};

const StatTile: FC<StatTileProps> = ({ label, suffix, value }) => {
  // #region hooks start
  // #endregion hooks end

  // #region logic functions start
  // #endregion logic functions end

  // #region useEffect functions start
  // #endregion useEffect functions end

  // #region render functions start
  return (
    <Card className="rounded-[24px] border-white/10 bg-white/6 backdrop-blur-sm">
      <Statistic
        formatter={(currentValue) => {
          return <span className="text-white">{currentValue}</span>;
        }}
        suffix={suffix}
        title={<span className="text-slate-400">{label}</span>}
        value={value}
      />
    </Card>
  );
  // #endregion render functions end
};

const AstronautSprite: FC<AstronautSpriteProps> = ({
  actor,
  radius,
  stageHeight,
}) => {
  // #region hooks start
  // #endregion hooks end

  // #region logic functions start
  const horizon = clamp(actor.y / Math.max(stageHeight, 1), 0, 1);
  // #endregion logic functions end

  // #region useEffect functions start
  // #endregion useEffect functions end

  // #region render functions start
  return (
    <div
      className="pointer-events-none absolute z-30"
      style={{
        left: actor.x,
        top: actor.y,
        transform: `translate(-50%, -50%) rotate(${actor.tilt}deg)`,
      }}
    >
      <div
        className="absolute inset-0 rounded-full"
        style={{
          background:
            "radial-gradient(circle, rgba(125,211,252,0.28), rgba(99,102,241,0.12) 55%, transparent 74%)",
          filter: "blur(4px)",
          height: radius * 2.2,
          left: -radius * 1.1,
          top: -radius * 1.1,
          width: radius * 2.2,
        }}
      />

      <div className="relative h-[120px] w-[96px]">
        <div
          className="absolute top-[10px] left-[18px] h-[52px] w-[52px] rounded-full border border-white/60 bg-[radial-gradient(circle_at_35%_35%,#e0f2fe,#c084fc_62%,#312e81)] shadow-[0_0_35px_rgba(129,140,248,0.55)]"
          style={{ transform: `scale(${1 + horizon * 0.06})` }}
        >
          <div className="absolute top-[8px] left-[8px] h-[34px] w-[34px] rounded-full bg-[radial-gradient(circle_at_35%_35%,#111827,#0f172a_62%,#020617)]">
            <div className="absolute top-[10px] left-[9px] h-[12px] w-[16px] rounded-full bg-cyan-200/85 blur-[1px]" />
          </div>
        </div>

        <div className="absolute top-[54px] left-[28px] h-[34px] w-[32px] rounded-[16px] border border-white/20 bg-gradient-to-b from-white via-slate-200 to-slate-400 shadow-[0_12px_30px_rgba(148,163,184,0.35)]" />
        <div className="absolute top-[58px] left-[16px] h-[12px] w-[18px] rounded-full bg-slate-100 shadow-[0_0_14px_rgba(255,255,255,0.35)]" />
        <div className="absolute top-[58px] left-[54px] h-[12px] w-[18px] rounded-full bg-slate-100 shadow-[0_0_14px_rgba(255,255,255,0.35)]" />
        <div className="absolute top-[86px] left-[29px] h-[26px] w-[10px] rounded-full bg-slate-200" />
        <div className="absolute top-[86px] left-[49px] h-[26px] w-[10px] rounded-full bg-slate-200" />

        <div className="absolute top-[104px] left-[33px] h-[20px] w-[8px] rounded-full bg-gradient-to-b from-cyan-300 to-indigo-500 blur-[0.5px]" />
        <div className="absolute top-[104px] left-[47px] h-[24px] w-[8px] rounded-full bg-gradient-to-b from-fuchsia-300 to-orange-400 blur-[0.5px]" />
      </div>
    </div>
  );
  // #endregion render functions end
};

const PretextCosmicPage: FC<PretextCosmicPageProps> = () => {
  // #region hooks start
  const stageRef = useRef<HTMLDivElement | null>(null);
  const targetRef = useRef({ x: 540, y: 280 });
  const animationFrameRef = useRef<number | null>(null);
  const [stageRect, setStageRect] = useState<StageRect>({
    height: 720,
    width: 1180,
  });
  const [gravityRadius, setGravityRadius] = useState(132);
  const [dualCore, setDualCore] = useState(true);
  const [actor, setActor] = useState<ActorState>({
    tilt: -6,
    vx: 0,
    vy: 0,
    x: 540,
    y: 280,
  });
  // #endregion hooks end

  // #region logic functions start
  const preparedBody = useMemo(() => {
    return prepareWithSegments(COSMIC_COPY, BODY_FONT);
  }, []);

  const rawLineWidth = useMemo(() => {
    return round(getSingleLineWidth(preparedBody));
  }, [preparedBody]);

  const projection = useMemo(() => {
    return buildProjection(
      preparedBody,
      stageRect,
      actor,
      gravityRadius,
      dualCore,
    );
  }, [actor, dualCore, gravityRadius, preparedBody, stageRect]);

  const reflowDensity = useMemo(() => {
    return (
      round(
        (projection.fragments.length / Math.max(projection.consumedRows, 1)) *
          100,
      ) / 100
    );
  }, [projection]);

  const usableWidth = useMemo(() => {
    return round(
      Math.min(stageRect.width - STAGE_PADDING_X * 2, MAX_TEXT_WIDTH),
    );
  }, [stageRect.width]);
  // #endregion logic functions end

  // #region useEffect functions start
  const handleAnimationStep = useEffectEvent((time: number) => {
    setActor((currentActor) => {
      const boundsWidth = stageRect.width;
      const boundsHeight = stageRect.height;
      const target = targetRef.current;
      const nextX = lerp(currentActor.x, target.x, 0.12);
      const nextY = lerp(currentActor.y, target.y, 0.12);
      const bob = Math.sin(time / 280) * 4;
      const vx = nextX - currentActor.x;
      const vy = nextY - currentActor.y;

      return {
        tilt: clamp(vx * 2.6, -18, 18),
        vx,
        vy,
        x: clamp(nextX, 120, Math.max(boundsWidth - 120, 120)),
        y: clamp(nextY + bob, 140, Math.max(boundsHeight - 140, 140)),
      } satisfies ActorState;
    });
  });

  useEffect(() => {
    const node = stageRef.current;

    if (node === null) {
      return undefined;
    }

    const observer = new ResizeObserver((entries) => {
      const entry = entries[0];

      if (entry === undefined) {
        return;
      }

      const nextWidth = entry.contentRect.width;
      const nextHeight = entry.contentRect.height;
      setStageRect({ height: nextHeight, width: nextWidth });
      targetRef.current = {
        x: clamp(targetRef.current.x, 120, Math.max(nextWidth - 120, 120)),
        y: clamp(targetRef.current.y, 140, Math.max(nextHeight - 140, 140)),
      };
    });

    observer.observe(node);

    return () => {
      observer.disconnect();
    };
  }, []);

  useEffect(() => {
    setLocale("en");

    const animate = (time: number) => {
      handleAnimationStep(time);
      animationFrameRef.current = requestAnimationFrame(animate);
    };

    animationFrameRef.current = requestAnimationFrame(animate);

    return () => {
      if (animationFrameRef.current !== null) {
        cancelAnimationFrame(animationFrameRef.current);
      }

      clearCache();
      setLocale(undefined);
    };
  }, []);
  // #endregion useEffect functions end

  // #region render functions start
  const handlePointerMove = (event: PointerEvent<HTMLDivElement>) => {
    const rect = event.currentTarget.getBoundingClientRect();

    targetRef.current = {
      x: clamp(event.clientX - rect.left, 120, Math.max(rect.width - 120, 120)),
      y: clamp(event.clientY - rect.top, 140, Math.max(rect.height - 140, 140)),
    };
  };

  const handlePointerLeave = () => {
    targetRef.current = {
      x: stageRect.width * 0.56,
      y: stageRect.height * 0.38,
    };
  };

  return (
    <div className="min-h-screen bg-[#060816] px-4 py-6 text-white md:px-8">
      <style>
        {`
          @keyframes cosmic-twinkle {
            0%, 100% { transform: scale(1); opacity: var(--star-opacity); }
            50% { transform: scale(1.8); opacity: 0.95; }
          }
        `}
      </style>

      <div className="mx-auto flex w-full max-w-[1500px] flex-col gap-6">
        <Card className="overflow-hidden border border-white/10 bg-[linear-gradient(135deg,rgba(15,23,42,0.88),rgba(76,29,149,0.62)_48%,rgba(8,47,73,0.9))] shadow-[0_24px_100px_rgba(14,165,233,0.12)]">
          <Row align="middle" gutter={[24, 24]}>
            <Col span={24} xl={16}>
              <Space className="w-full" direction="vertical" size="large">
                <Space size={[8, 8]} wrap>
                  <Tag color="cyan">New Demo</Tag>
                  <Tag color="magenta">layoutNextLine</Tag>
                  <Tag color="gold">Official-demo inspired</Tag>
                </Space>

                <div>
                  <Typography.Title className="mb-3! text-[42px]! leading-[0.96]! text-white md:text-[58px]!">
                    Pretext Cosmic Drift
                  </Typography.Title>
                  <Typography.Paragraph className="max-w-[860px] text-[16px] text-slate-200 md:text-[18px]">
                    Mouse over the stage and drag the pilot through the
                    paragraph. The text reflows around the gravity core in real
                    time, and nearby fragments heat up visually. This page
                    borrows its DNA from the official editorial and orb demos,
                    but pushes it into a more theatrical direction.
                  </Typography.Paragraph>
                </div>
              </Space>
            </Col>

            <Col span={24} xl={8}>
              <div className="rounded-[28px] border border-white/10 bg-black/25 p-5 backdrop-blur-sm">
                <div className="mb-3 text-xs tracking-[0.28em] text-cyan-200 uppercase">
                  Why it works
                </div>
                <div className="space-y-3 text-sm leading-6 text-slate-200">
                  <div>`prepareWithSegments()` caches measurement once.</div>
                  <div>
                    `layoutNextLine()` materializes text fragment-by-fragment
                    for each free slot on a row.
                  </div>
                  <div>
                    The moving astronaut is just geometry. Pretext handles the
                    reflow math.
                  </div>
                </div>
              </div>
            </Col>
          </Row>
        </Card>

        <Row gutter={[16, 16]}>
          <Col span={24} xl={7}>
            <Space className="w-full" direction="vertical" size="middle">
              <Card className="border border-white/10 bg-white/6 text-white backdrop-blur-sm">
                <Space className="w-full" direction="vertical" size="large">
                  <div>
                    <Typography.Title className="mb-2! text-white" level={4}>
                      Control Deck
                    </Typography.Title>
                    <Typography.Paragraph className="text-slate-300">
                      Bigger radius means wider exclusion geometry. Dual core
                      mode adds a trailing echo field so the text can split into
                      multiple live channels on the same row.
                    </Typography.Paragraph>
                  </div>

                  <div>
                    <div className="mb-2 flex items-center justify-between text-sm text-slate-300">
                      <span>Gravity radius</span>
                      <span>{gravityRadius}px</span>
                    </div>
                    <Slider
                      max={190}
                      min={88}
                      value={gravityRadius}
                      onChange={setGravityRadius}
                    />
                  </div>

                  <div className="flex items-center justify-between rounded-[20px] border border-white/10 bg-black/20 px-4 py-3">
                    <div>
                      <div className="text-sm font-semibold text-white">
                        Dual core mode
                      </div>
                      <div className="text-xs text-slate-400">
                        Adds a secondary echo obstacle behind the pilot
                      </div>
                    </div>
                    <Switch checked={dualCore} onChange={setDualCore} />
                  </div>
                </Space>
              </Card>

              <Row gutter={[12, 12]}>
                <Col span={12}>
                  <StatTile
                    label="Fragments"
                    value={projection.fragments.length}
                  />
                </Col>
                <Col span={12}>
                  <StatTile label="Rows" value={projection.consumedRows} />
                </Col>
                <Col span={12}>
                  <StatTile
                    label="Line width"
                    suffix="px"
                    value={rawLineWidth}
                  />
                </Col>
                <Col span={12}>
                  <StatTile label="Canvas" suffix="px" value={usableWidth} />
                </Col>
              </Row>

              <Card className="border border-white/10 bg-[linear-gradient(180deg,rgba(12,18,34,0.9),rgba(17,24,39,0.55))] text-white">
                <Typography.Title className="text-white" level={4}>
                  Spectacle Notes
                </Typography.Title>
                <div className="space-y-2 text-sm leading-6 text-slate-300">
                  <div>Average fragments per occupied row: {reflowDensity}</div>
                  <div>
                    Nearby fragments are brightened from obstacle distance, not
                    random animation.
                  </div>
                  <div>
                    This is a second route, so the earlier Pretext overview page
                    stays untouched.
                  </div>
                </div>
              </Card>
            </Space>
          </Col>

          <Col span={24} xl={17}>
            <div
              ref={stageRef}
              className="relative min-h-[78vh] overflow-hidden rounded-[36px] border border-cyan-400/15 bg-[radial-gradient(circle_at_20%_10%,rgba(34,211,238,0.16),transparent_25%),radial-gradient(circle_at_78%_18%,rgba(168,85,247,0.28),transparent_24%),radial-gradient(circle_at_62%_70%,rgba(59,130,246,0.18),transparent_26%),linear-gradient(180deg,#040612_0%,#090b1e_48%,#090d19_100%)] shadow-[0_24px_120px_rgba(15,23,42,0.55)]"
              onPointerLeave={handlePointerLeave}
              onPointerMove={handlePointerMove}
            >
              <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.03)_1px,transparent_1px)] bg-[size:38px_38px] opacity-30" />
              <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,transparent_0%,transparent_56%,rgba(0,0,0,0.45)_100%)]" />

              {STARS.map((star) => {
                return (
                  <div
                    key={star.id}
                    className="absolute rounded-full bg-white"
                    style={
                      {
                        "--star-opacity": `${star.opacity}`,
                        animation: `cosmic-twinkle ${star.duration}s ease-in-out ${star.delay}s infinite`,
                        height: star.size,
                        left: star.left,
                        opacity: star.opacity,
                        top: star.top,
                        width: star.size,
                      } as React.CSSProperties
                    }
                  />
                );
              })}

              <div
                className="pointer-events-none absolute rounded-full border border-cyan-200/25"
                style={{
                  boxShadow:
                    "0 0 120px rgba(56,189,248,0.16), inset 0 0 24px rgba(244,114,182,0.08)",
                  height: gravityRadius * 2.2,
                  left: actor.x - gravityRadius * 1.1,
                  top: actor.y - gravityRadius * 1.1,
                  width: gravityRadius * 2.2,
                }}
              />

              <div
                className="pointer-events-none absolute rounded-full bg-[radial-gradient(circle,rgba(192,132,252,0.22),transparent_68%)] blur-[1px]"
                style={{
                  height: gravityRadius * 3,
                  left: actor.x - gravityRadius * 1.5,
                  top: actor.y - gravityRadius * 1.5,
                  width: gravityRadius * 3,
                }}
              />

              {projection.fragments.map((fragment) => {
                const glow = 10 + fragment.intensity * 32;
                const rotate = (fragment.intensity - 0.5) * 5 + actor.vx * 0.4;
                const hue = 200 - fragment.intensity * 120;

                return (
                  <div
                    key={fragment.id}
                    className="absolute text-[22px] leading-[28px] whitespace-pre select-none"
                    style={{
                      color: `hsla(${hue}, 90%, ${72 + fragment.intensity * 14}%, ${0.76 + fragment.intensity * 0.22})`,
                      font: BODY_FONT,
                      left: fragment.x,
                      textShadow: `0 0 ${glow}px rgba(125,211,252,${0.1 + fragment.intensity * 0.34})`,
                      top: fragment.y,
                      transform: `translateZ(0) rotate(${rotate}deg) scale(${1 + fragment.intensity * 0.04})`,
                      transformOrigin: "left center",
                      width: fragment.width,
                    }}
                  >
                    {fragment.text}
                  </div>
                );
              })}

              <AstronautSprite
                actor={actor}
                radius={gravityRadius}
                stageHeight={stageRect.height}
              />

              <div className="pointer-events-none absolute top-6 right-6 rounded-full border border-white/12 bg-black/35 px-4 py-2 text-xs tracking-[0.24em] text-cyan-100 uppercase backdrop-blur-sm">
                Move your mouse through the nebula
              </div>

              <div className="pointer-events-none absolute bottom-5 left-1/2 -translate-x-1/2 rounded-full border border-white/10 bg-black/35 px-5 py-2 text-xs text-slate-300 backdrop-blur-sm">
                Powered by Pretext line routing, not DOM measurement
              </div>
            </div>
          </Col>
        </Row>
      </div>
    </div>
  );
  // #endregion render functions end
};

export type { PretextCosmicPageProps };
export { PretextCosmicPage };
